### ISSUE TITLE
Merge state from the same company

### ISSUE THREAD

**Issue by Windsooon** [resumejob/JobTracker#2]
In the current version, emails from the same company would be split into different rows, However, this is not what the user expects. It would be better to merge emails to the same row and only show the time in different states. For example

| Company Name | State |
|---------------|---------------|
| ABC                 | - Applied: 7.12<br>- Next Round: 7.20<br>- Offer: 8.10      |

**Comment by Garenbbbb** [comment]
It is a good idea to track different positions applied for one company.
